ccj7/coffee-clip

front/pages/shop/signup.tsx
@naonmr  フロント側修正したので、念の為メンションします！
FIX #208
=> Shop S-Signup: ポスト先のパスを修正 #208 （エラーメッセージ追加）

front/components/ShopTopPage.tsx
@mei-omomo お手数ですがご確認お願いします 🙇 
修正したものたち👇
FIX #193 #197 #210 
（ @naonmr 共有用のメンションです）
=> U-008 / S-004 あげてもらったバグの修正

server/__test__/shops/_get.ts, server/shop/controller.ts, server/shop/route.ts
@Maho-Miyazawa プルリクの確認をお願いします 🙇 
ユーザーがそのショップをフォローしているかを確認するデータを返すエンドポイントを追加しました。
FIX #164
※テストも追加済み
※元々使っていた getShopも怖いので残してあります
（ @Motoki-tech 共有のためのメンションです）
=> Shopをフォローしているかどうかのステータスチェック追加

front/pages/user/mypage.tsx, front/pages/user/topPage/[handle_name]/index.tsx
- U-006の画面に飛んだ時に、自分のアカウントだった場合は、MyPage（U-004）にリダイレクトするように修正
- MyPageの、webkit-backdropFilter -> webkit-backdropfilterに修正（Warning修正）
- MyPageが全体的にprettierが適用された模様
FIX #204
=> MyPageにリダイレクトするよう修正

front/components/ShopTopPage.tsx, front/index.d.ts, front/initial_data/shopInitialDdata.ts
=> Shop詳細ページでフォロー中かによってボタンを出し分けするように修正

front/pages/shop/fix-shopinfo/[handle_name]/index.tsx
ShopIDのフォームを削除しました。ご確認お願いします 🙇 
FIX #187
=> fix: ショップIDを変更できないように修正

front/pages/shop/signup.tsx
@mei-omomo Shop側のSignup画面にも反映しました 🙇 ご確認をお願いします。
=> Shop: Signup画面にCSS追加

front/components/user/ShopCard.tsx, front/pages/user/shoplist.tsx
=> css: user/shoplistとコンポーネントのShopCard

front/pages/user/signin.tsx, front/pages/user/signup.tsx
=> Front: User Login画面のCSS

server/shop/shops.json, server/user/users.json
- users.jsonと、shops.jsonファイルの中身を充実させました（画像含む）
- S3に画像を追加
- user用icon：13個
- shop用icon：10個
- reviewsのimage、recommendationsのimage、selling-pointのimage：共通で15個
FIX #202 
FIX #221
=> Server: seed用のファイルを充実させる

front/pages/shop/signin.tsx, front/pages/user/signin.tsx, front/pages/user/signup.tsx
@mei-omomo ご確認お願いします！
* next.jsのLinkタグを使っていたものをChakraのLinkに変更しました
* Shopのログイン画面作成しました
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201750414055670) by [Unito](https://www.unito.io)
=> Front: Shop側のログイン画面作成

front/components/ShopTopPage.tsx, front/pages/user/shop-top-page/[handle_name]/index.tsx
=> css: shopTopPageにcssをつけた

front/components/user/UserResultCard.tsx, front/pages/user/search.tsx
=> User: 検索結果画面 CSS追加

front/components/ImageUpload.tsx, front/pages/user/new-review.tsx
=> Front: ログの新規投稿 修正

front/pages/shop/stripe-success.tsx, front/pages/shop/stripe.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201750414516363) by [Unito](https://www.unito.io)
=> feat: shop側の画面作成

server/__test__/shops/_get.ts, server/__test__/users/_get.ts, server/__test__/users/_put.ts
- users.jsonの修正に伴いテストを修正
- _get.ts
- _put.ts 
- shops.jsonの修正に伴いテストを修正
- _get.ts
- prettierが適用された模様
=> Server: testコード修正

front/components/Button.tsx, front/components/user/ShopCard.tsx, front/pages/user/favorite-shops.tsx
✨ お気に入りのショップ一覧の並び方を、ショップ一覧に合わせました。
✨ 昨日Paddyが送ってくれたピンタレスト参考に、ShopCardコンポーネントの画像の大きさを大きくしました。
✨ Buttonコンポーネントのボタンの色を変更して、hover時の色も変更しました。
- - - -
=> Css：front user favorite shops

front/components/ImageUpload.tsx, front/components/InputForm.tsx, front/pages/shop/fix-shopinfo/[handle_name]/index.tsx, front/pages/shop/signin.tsx, front/pages/shop/signup.tsx, front/pages/user/new-review.tsx, front/pages/user/setting.tsx, front/pages/user/signin.tsx, front/pages/user/signup.tsx
- 誤字を修正しました
- thema -> theme
- prettierが適用されている箇所あり
FIX #213
=> chore: 誤字修正(thema->theme)

front/pages/user/mypage.tsx, front/pages/user/topPage/[handle_name]/index.tsx
整えました。
マージするとフォローの部分のボタンは緑色になる予定です！
「フォロー中」と「フォローする」でボタンの色を変えたい気もするけど、細かい部分なので一旦プルリクエスト出します！
=> CSS：U-006 フォローしている人のページ　

front/components/user/LogCard.tsx, front/index.d.ts, front/initial_data/userInitialData.ts, front/pages/user/signup.tsx, front/pages/user/timeline.tsx
FIX #252
@Maho-Miyazawa ご確認お願いします〜。
=> User Signup後のメッセージがリロードしないとでない件を修正

front/pages/_app.tsx, front/pages/user/topPage/[handle_name]/index.tsx
@mei-omomo @Maho-Miyazawa  ご確認お願いします〜。
=> Axiosのデータ型を追加しました

front/pages/shop/dashboard.tsx, front/pages/shop/top-page/[handle_name]/index.tsx
@mei-omomo ご確認お願いします :bowing_man: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201758110019791) by [Unito](https://www.unito.io)
=> Shop: 型定義 & UI修正

front/pages/user/onlineShop.tsx, front/pages/user/payment-success.tsx, server/stripe/route.ts
支払い成功したら、「支払い完了しました」と表示するようにしました。
※備考
支払い失敗したら以下のような表示になります。お見知り置きを！
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201758109843125) by [Unito](https://www.unito.io)
=> feat:リダイレクト先の変更と、支払い成功画面表示

front/components/user/OnlineShopCard.tsx, front/components/user/UserHeader.tsx, front/pages/_app.tsx, front/pages/user/onlineShop.tsx
・メニューにオンラインショップを足して、SP時にメニューをハンバーガーメニューの中に入れました。
・オンランショップページのcssを調整しました。
=> css: user側のヘッダーの調整とオンラインショップの調整

front/components/TextArea.tsx, front/pages/user/new-review.tsx
- description: 必須 にしました。
- https://github.com/ccj7/coffee-clip/issues/226
FIX #226
=> Front: User 新規ログ投稿 テキストエリアに変更 & バリデーション追加

front/pages/shop/signin.tsx, front/pages/shop/signup.tsx, front/pages/user/signin.tsx, front/pages/user/signup.tsx
=> Signup, Signin画面にバリデーション追加

front/components/shop/Header.tsx
origin style/shop-header
ヘッダーの色を調節しました！
=> feat: headerの色調整

front/pages/user/setting.tsx
- ユーザープロフィールの、ユーザーネーム（display_name）にバリデーションを追加
#185
=> U-003: userプロフィール編集画面にバリデーション追加

front/components/ImageUpload.tsx
FIX #184
「upload」ボタン以外を押しても反応してしまう件を修正しました！
=> Bugfix/compornent image apload：「upload」ボタン以外を押しても反応してしまう件を修正しました！

server/index.ts, server/shop/controller.ts, server/user/controller_get.ts, server/user/controller_post.ts, server/user/controller_put.ts
=> connectToDBをindex.tsで一括処理に変更

front/pages/user/mypage.tsx
fix #242 
・マイページに新規投稿ボタンがなかったので追加しました。
・なおさんが作ってくれたMyLogCardに変更。（添付画像は変える前です）
=> feat: mypageにも新規投稿ボタンを追加

front/pages/user/setting.tsx, front/pages/user/topPage/[handle_name]/index.tsx
FIX #194 
FIX #277
キャンセルボタンを追加しました。
ついでにtoppage/:handle_nameのLogcardをMyLogCardに変更しました
=> Fix/front user setting　キャンセルボタンを追加

front/components/InputForm.tsx, front/components/Message.tsx, front/pages/shop/fix-shopinfo/[handle_name]/index.tsx
変更点
- shop名（ディスプレイネーム）: 必須
- 営業時間textareaに変更
- おすすめのいっぱいのdescription: textareaに変更
- お店の魅力のtext: textareaに変更
- デザイン調整
- 保存後はフォームを非表示
=> Shop 編集画面調整

front/components/Alert.tsx, front/pages/user/signup.tsx
=> feat: alertコンポーネントを作成

server/shop/controller.ts, server/user/controller_get.ts
=> Server: statusコードを削除

front/pages/shop/fix-shopinfo/[handle_name]/index.tsx
@mei-omomo @naonmr キャンセルボタン追加したのでご確認お願いします。
FIX #203
=> feet: 店舗情報編集 キャンセルボタンを追加

front/pages/user/setting.tsx
@mei-omomo @naonmr プロフィール編集画面にCSS追加しました 🙇  ご確認お願いします。
=> Front: User プロフィール編集画面 CSS追加 & 型定義追加

front/components/BoxMessage.tsx, front/pages/user/onlineShop.tsx, front/pages/user/payment-success.tsx
@mei-omomo ご確認お願いします 🙇 
- FIX #300 
- 支払い完了画面のデザイン調整
- カードレイアウトでメッセージを表示する際のコンポーネント追加
=> Front: Online Shop販売店リンク修正 & 支払い完了画面のデザイン調整

front/pages/index.tsx
=> css: indexページ

front/components/ShopTopPage.tsx
@mei-omomo ご確認お願いします〜。
FIX #301
=> Fornt: コーヒー豆のタブ削除 & CSS 微調整

front/pages/shop/fix-shopinfo/[handle_name]/index.tsx, front/pages/user/new-review.tsx, front/pages/user/setting.tsx, front/pages/user/timeline.tsx
@mei-omomo 保存したときの表示を揃えました。
新規投稿のデザインも調整しました。
FIX #315 
FIX #310 
FIX #314
=> Front: 保存後のメッセージの表示を揃えた

front/pages/shop/dashboard.tsx
FIX #296
@mahomiyata  確認お願いします〜〜〜
=> front: ダッシュボードのボタンの位置を調整

front/components/ShopTopPage.tsx
=> feat: インスタアイコンのfocusを適切なサイズに調節

front/components/shop/Header.tsx, front/components/user/UserHeader.tsx
@mei-omomo ご確認お願いします〜。
FIX #199
=> fix: COFFEE CLIPの文字をホバーしたときの挙動を修正

front/pages/user/favorite-shops.tsx
FIX #311
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201763670225648) by [Unito](https://www.unito.io)
=> bugfix: お気に入りショップが0件の時、メッセージボックスを表示する

front/components/user/LogCard.tsx, front/components/user/ShopCard.tsx, front/pages/index.tsx, front/pages/shop/dashboard.tsx, front/pages/shop/signin.tsx, front/pages/shop/signup.tsx, front/pages/shop/top-page/[handle_name]/index.tsx, front/pages/user/favorite-shops.tsx, front/pages/user/mypage.tsx, front/pages/user/new-review.tsx, front/pages/user/onlineShop.tsx, front/pages/user/search.tsx, front/pages/user/setting.tsx, front/pages/user/shop-top-page/[handle_name]/index.tsx, front/pages/user/shoplist.tsx, front/pages/user/signin.tsx, front/pages/user/signup.tsx, front/pages/user/timeline.tsx, front/pages/user/topPage/[handle_name]/index.tsx
=> fornt: メタタグの削除とホバー対応

front/pages/user/mypage.tsx, front/pages/user/topPage/[handle_name]/index.tsx
=> bugfix: ホバー、カーソル関連の修正

server/schema/shopSchema.ts, server/shop/controller.ts
@Maho-Miyazawa バグ修正しました。ご確認お願いします。
FIX #295 
Co-authored-by: Motoki Mizuno <Motoki-tech@users.noreply.github.com>
=> Shop: 店舗情報を更新したときに画像が消えてしまうのを修正

front/components/Image.tsx, front/components/ShopTopPage.tsx, front/pages/user/shop-top-page/[handle_name]/index.tsx
=> Front: U-008 / S-004 ヘッダー の固定が取れてしまうのを修正

front/components/ShopTopPage.tsx, front/pages/shop/top-page/[handle_name]/index.tsx
FIX #328
FIX #329
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201768681931589) by [Unito](https://www.unito.io)
=> Feat: 公開非公開のステータス表示・お気に入りボタンを押したときにアラート表示

front/components/ShopTopPage.tsx
@mei-omomo 画像の枠線削除しました。
FIX #337
=> fix: 画像の枠線削除

README.md
@Maho-Miyazawa @naonmr @mei-omomo @Motoki-tech
ReadMeをとりあえず書きました。
追加必要なことがあればご連絡ください。
FIX #218
=> ReadMe書きました

front/components/ShopTopPage.tsx, front/pages/user/setting.tsx, front/pages/user/shop-top-page/[handle_name]/index.tsx, front/pages/user/timeline.tsx
@mei-omomo タイトル修正しました。気になるところなければマージをお願いします 🙇  
FIX #360
=> 一部のタイトルを修正

README.md, server/.eslintrc.json, server/.prettierrc.json, server/db-connection.ts, server/index.ts, server/package-lock.json, server/package.json, server/s3.ts, server/schema/shopSchema.ts, server/schema/userSchema.ts, server/shop/controller.ts, server/shop/route.ts, server/shop/seed.ts, server/shop/shops.json, server/stripe/route.ts, server/tsconfig.json, server/user/controller_get.ts, server/user/controller_post.ts, server/user/controller_put.ts, server/user/route.ts, server/user/seed.ts, server/user/users.json
- server側のTABの数を4->2に変更し、該当ファイルにprettierを適用
=> chore: Prettierを適用
